import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    backgroundColor: '#F4B018',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 10,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 30,
  },
  formContainer: {
    flex: 1,
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 20,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  inputGroup: {
    marginBottom: 24,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4a6da7',
    marginBottom: 6,
  },
  fieldSubLabel: {
    fontSize: 12,
    color: '#95a5a6',
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 14,
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    color: '#34495e',
  },
  textArea: {
    height: 120,
    textAlignVertical: 'top',
    lineHeight: 20,
  },
  charCounter: {
    fontSize: 12,
    color: '#95a5a6',
    textAlign: 'right',
    marginTop: 4,
  },
  uploadButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  uploadButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F4B018',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  uploadButtonAlt: {
    backgroundColor: '#F4B018',
    borderWidth: 1,
    borderColor: '#d0d9e8',
  },
  uploadButtonDisabled: {
    opacity: 0.6,
  },
  uploadButtonText: {
    color: 'black',
    fontSize: 14,
    fontWeight: '500',
  },
  uploadButtonAltText: {
    color: '#4a6da7',
  },
  buttonIcon: {
    marginRight: 8,
  },
  filesContainer: {
    marginTop: 16,
  },
  filesListContent: {
    paddingRight: 16,
  },
  fileItem: {
    width: 100,
    marginRight: 12,
    alignItems: 'center',
    position: 'relative',
  },
  filePreview: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  documentPreview: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: '#f0f4ff',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  documentTypeText: {
    fontSize: 12,
    color: '#4a6da7',
    marginTop: 4,
    fontWeight: '500',
  },
  fileName: {
    fontSize: 12,
    color: '#34495e',
    textAlign: 'center',
    marginTop: 6,
    width: '100%',
  },
  removeFileButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  footer: {
    paddingHorizontal: 16,
    marginBottom: 30,
  },
  submitButton: {
    backgroundColor: '#F4B018',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#4a6da7',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  submitButtonDisabled: {
    backgroundColor: '#95a5c9',
  },
  submitButtonText: {
    color: 'black',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;