import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const COLORS = {
  PRIMARY: '#F4B018', // Orange for buttons
  ACCENT: '#F4B018',
  BACKGROUND: '#fff', // White background
  TEXT: '#333', // Primary text
  SECONDARY_TEXT: '#666', // Secondary text/icons
  PLACEHOLDER: '#999', // Placeholder text
  BORDER: '#ddd', // Borders
  DISABLED: '#ccc', // Disabled buttons
  SUCCESS: '#28a745', // Green for success
  ERROR: '#dc3545', // Red for errors
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  postContainer: {
    padding: 20,
    backgroundColor: COLORS.BACKGROUND,
  },
  headerSection: {
    width: '120%',
    alignSelf: 'center',
    paddingTop: 10,
    paddingBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 70,
    borderBottomRightRadius: 70,
    elevation: 5,
    backgroundColor: COLORS.ACCENT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.TEXT,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    marginBottom: 15,
    backgroundColor: '#f5f5f5',
    color: COLORS.TEXT,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  toggleLabel: {
    fontSize: 16,
    color: COLORS.TEXT,
    fontWeight: '600',
  },
  beforeAfterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  beforeAfterColumn: {
    width: '48%',
  },
  beforeAfterLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.TEXT,
    marginBottom: 5,
  },
  beforeAfterImageContainer: {
    position: 'relative',
    width: '100%',
    height: 120,
  },
  beforeAfterImage: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    resizeMode: 'cover',
  },
  beforeAfterRemoveButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 12,
    padding: 5,
  },
  beforeAfterPlaceholder: {
    width: '100%',
    height: 120,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  beforeAfterPlaceholderText: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    marginTop: 5,
  },
  mediaList: {
    marginBottom: 15,
  },
  mediaItemContainer: {
    position: 'relative',
    marginRight: 10,
    width: 120,
    height: 120,
  },
  mediaPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
    resizeMode: 'cover',
  },
  mediaButtonsContainer: {
    position: 'absolute',
    top: 5,
    right: 5,
    flexDirection: 'row',
  },
  mediaButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 12,
    padding: 5,
    marginLeft: 5,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  disabledButton: {
    backgroundColor: '#f5f5f5',
    opacity: 0.5,
  },
  actionText: {
    fontSize: 14,
    color: COLORS.PRIMARY,
    marginLeft: 5,
    fontWeight: '600',
  },
  disabledText: {
    color: COLORS.DISABLED,
  },
  detailSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.TEXT,
    marginBottom: 10,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  detailInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    marginLeft: 10,
    backgroundColor: '#f5f5f5',
    color: COLORS.TEXT,
  },
  locationButton: {
    flex: 1,
    padding: 10,
    marginLeft: 10,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    justifyContent: 'center',
  },
  locationButtonText: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'left',
  },
  categoryScrollView: {
    marginBottom: 10,
  },
  categoryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  categoryText: {
    fontSize: 14,
    color: COLORS.TEXT,
    marginRight: 5,
  },
  noCategories: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 10,
  },
  suggestedTagsContainer: {
    marginTop: 10,
  },
  suggestedTagsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.SECONDARY_TEXT,
    marginBottom: 5,
  },
  suggestedTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  suggestedTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  suggestedTagText: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    marginRight: 5,
  },
  fullWidthButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    marginBottom: 10,
  },
  fullWidthButtonText: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    marginLeft: 10,
    flex: 1,
  },
  documentsList: {
    marginBottom: 10,
  },
  documentItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 10,
    marginBottom: 5,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  documentName: {
    flex: 1,
    fontSize: 14,
    color: COLORS.TEXT,
    marginLeft: 10,
  },
  documentButton: {
    padding: 5,
  },
  uploadButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    backgroundColor: '#f5f5f5',
    marginRight: 10,
  },
  cancelButtonText: {
    fontSize: 16,
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  uploadSubmitButton: {
    flex: 1,
    padding: 15,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY,
    alignItems: 'center',
  },
  uploadSubmitButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  uploadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  uploadingText: {
    fontSize: 16,
    color: COLORS.TEXT,
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: COLORS.BACKGROUND,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    width: '80%',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.TEXT,
    marginBottom: 10,
  },
  modalMessage: {
    fontSize: 16,
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'center',
    marginBottom: 20,
  },
  successIcon: {
    marginBottom: 20,
  },
  editorPreview: {
    width: 200,
    height: 200,
    borderRadius: 8,
    marginBottom: 15,
    resizeMode: 'contain',
  },
  editorControl: {
    width: '100%',
    marginBottom: 15,
  },
  editorLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.TEXT,
    marginBottom: 5,
  },
  sliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sliderInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 8,
    padding: 8,
    marginHorizontal: 10,
    backgroundColor: '#f5f5f5',
    color: COLORS.TEXT,
    textAlign: 'center',
  },
  watermarkInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#f5f5f5',
    color: COLORS.TEXT,
  },
  editorButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  editorCancelButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    marginRight: 10,
    backgroundColor: '#f5f5f5',
  },
  editorCancelButtonText: {
    fontSize: 16,
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  editorApplyButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY,
    alignItems: 'center',
  },
  editorApplyButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  noDocuments: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    textAlign: 'center',
    marginBottom: 10,
  },
  addDocumentButton: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY,
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
  },
  addDocumentButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  closeModalButton: {
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    backgroundColor: '#f5f5f5',
    width: '100%',
  },
  closeModalButtonText: {
    fontSize: 16,
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  customCategoryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  customCategoryInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#f5f5f5',
    color: COLORS.TEXT,
    marginRight: 10,
  },
  addCustomCategoryButton: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY,
    alignItems: 'center',
  },
  addCustomCategoryButtonText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
  },
  commonCategoriesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.TEXT,
    marginBottom: 10,
  },
  commonCategoriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15,
  },
  commonCategory: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  selectedCategory: {
    backgroundColor: '#e6f0fa',
    borderColor: COLORS.PRIMARY,
  },
  commonCategoryText: {
    fontSize: 14,
    color: COLORS.SECONDARY_TEXT,
    marginRight: 5,
  },
  selectedCategoryText: {
    color: COLORS.PRIMARY,
    fontWeight: '600',
  },
});