import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        padding: 20,
    },
    errorText: {
        fontSize: 18,
        color: '#ff3b30',
        marginBottom: 20,
    },
    backButtonFallback: {
        backgroundColor: '#0288D1',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    backButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    header: {
        backgroundColor: '#F4B018',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    backButtonIcon: {
        padding: 5,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
    headerIconButton: {
        padding: 5,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
    },
    dropdownMenu: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 50,
        right: 16,
        backgroundColor: '#fff',
        borderRadius: 8,
        width: 160,
        paddingVertical: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    dropdownIcon: {
        marginRight: 10,
    },
    dropdownText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    coverContainer: {
        height: 180,
        width: '100%',
    },
    coverGradient: {
        height: '100%',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    coverOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 20,
    },
    profileImageContainer: {
        position: 'absolute',
        bottom: -50,
        alignItems: 'center',
    },
    profileImageWrapper: {
        borderRadius: 60,
        padding: 5,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 8,
    },
    profileImage: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 4,
        borderColor: '#fff',
    },
    onlineIndicator: {
        position: 'absolute',
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#4CAF50',
        borderWidth: 3,
        borderColor: '#fff',
        bottom: 12,
        right: 8,
    },
    profileInfoCard: {
        backgroundColor: '#fff',
        marginTop: 60,
        marginHorizontal: 12,
        borderRadius: 12,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    userInfoSection: {
        alignItems: 'center',
        marginBottom: 16,
    },
    nameText: {
        fontSize: 24,
        fontWeight: '700',
        color: '#333',
        marginBottom: 4,
    },
    professionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    professionText: {
        color: '#0288D1',
        fontSize: 16,
        fontWeight: '500',
        marginLeft: 5,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    infoText: {
        color: '#666',
        fontSize: 14,
        marginLeft: 6,
    },
    bioText: {
        color: '#333',
        fontSize: 15,
        textAlign: 'center',
        marginTop: 8,
        lineHeight: 22,
    },
    professionalSection: {
        marginTop: 20,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    sectionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    professionalSectionTitle: {
        fontSize: 17,
        fontWeight: '600',
        color: '#333',
        marginLeft: 6,
    },
    skillsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    skillBadge: {
        backgroundColor: '#E1F5FE',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginRight: 8,
        marginBottom: 8,
    },
    skillText: {
        color: '#0288D1',
        fontSize: 13,
        fontWeight: '500',
    },
    showMoreButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
    },
    showMoreText: {
        color: '#0288D1',
        fontSize: 14,
        fontWeight: '500',
        marginRight: 4,
    },
    mapContainer: {
        height: 200,
        marginTop: 20,
        borderRadius: 12,
        overflow: 'hidden',
    },
    map: {
        ...StyleSheet.absoluteFillObject,
    },
    mapErrorText: {
        color: '#ff3b30',
        textAlign: 'center',
        marginTop: 20,
        fontSize: 14,
    },
    ratingCard: {
        marginTop: 20,
        borderRadius: 12,
        overflow: 'hidden',
    },
    ratingGradient: {
        padding: 16,
    },
    ratingHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    ratingTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginLeft: 6,
    },
    ratingValue: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
    },
    ratingNumber: {
        fontSize: 30,
        fontWeight: '700',
        color: '#333',
        marginRight: 12,
    },
    ratingStarsContainer: {
        flex: 1,
    },
    ratingStarsRow: {
        flexDirection: 'row',
    },
    ratingCount: {
        color: '#666',
        fontSize: 12,
        marginTop: 2,
    },
    userRatingContainer: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: 'rgba(0,0,0,0.1)',
    },
    userRatingTitle: {
        fontSize: 15,
        fontWeight: '500',
        color: '#444',
        marginBottom: 8,
    },
    userRatingStars: {
        flexDirection: 'row',
    },
    starContainer: {
        marginRight: 6,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        padding: 12,
        backgroundColor: '#f9f9f9',
        borderRadius: 12,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statNumber: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
    },
    statLabel: {
        fontSize: 13,
        color: '#666',
        marginTop: 4,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginTop: 16,
        marginBottom: 20,
        paddingHorizontal: 8,
    },
    actionButtonsContainerMulti: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 16,
        marginBottom: 20,
        paddingHorizontal: 8,
    },
    messageButton: {
        minWidth: 120,
        flexDirection: 'row',
        backgroundColor: '#0288D1',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    messageButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        textAlign: 'center',
    },
    orderButton: {
        minWidth: 120,
        flexDirection: 'row',
        backgroundColor: '#0288D1',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    orderButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        textAlign: 'center',
    },
    hireButton: {
        minWidth: 120,
        flexDirection: 'row',
        backgroundColor: '#0288D1',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    hireButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        textAlign: 'center',
    },
    ordersButton: {
        minWidth: 120,
        flexDirection: 'row',
        backgroundColor: '#0288D1',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    ordersButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        textAlign: 'center',
    },
    buttonWithBadge: {
        position: 'relative',
        marginHorizontal: 4,
        marginTop: 8,
    },
    badge: {
        position: 'absolute',
        top: -6,
        right: -6,
        backgroundColor: '#D32F2F',
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: '#fff',
    },
    badgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '600',
        textAlign: 'center',
    },
    editProfileButton: {
        minWidth: 120,
        flexDirection: 'row',
        backgroundColor: '#0288D1',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 4,
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    editProfileButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
        textAlign: 'center',
    },
    buttonIcon: {
        marginRight: 8,
    },
    postsSection: {
        marginTop: 20,
        paddingHorizontal: 12,
        paddingBottom: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    seeAllButton: {
        padding: 4,
    },
    seeAllText: {
        color: '#0288D1',
        fontSize: 14,
        fontWeight: '500',
    },
    emptyPostsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
        backgroundColor: '#f9f9f9',
        borderRadius: 12,
    },
    emptyPostsText: {
        fontSize: 16,
        color: '#999',
        marginTop: 12,
    },
});

export default styles;