import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const cardWidth = (width - 48) / 2;

const COLORS = {
  LIGHT_BG: '#F9FAFB',
  DARK_BG: '#1F2937',
  LIGHT_TEXT: '#1F2937',
  DARK_TEXT: '#F9FAFB',
  ACCENT: '#F4B018',
  PRIMARY: '#007AFF',
  GRAY: '#6B7280',
  DARK_GRAY: '#4B5563',
  LIGHT_GRAY: '#F3F4F6',
  BORDER: '#E5E7EB',
  DARK_BORDER: '#374151',
  ERROR: '#EF4444',
};

const SPACING = {
  small: 8,
  medium: 12,
  large: 16,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.LIGHT_BG,
  },
  darkContainer: {
    backgroundColor: COLORS.DARK_BG,
  },
  keyboardAvoidingContainer: {
    flex: 1,
  },
  searchBarContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2000,
    backgroundColor: COLORS.LIGHT_BG,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 80,
  },
  section: {
    marginBottom: SPACING.large,
    paddingHorizontal: SPACING.large,
    backgroundColor: 'transparent',
  },
  searchSection: {
    backgroundColor: COLORS.ACCENT,
    borderRadius: 12,
    paddingVertical: SPACING.medium,
    paddingHorizontal: 0,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.LIGHT_TEXT,
    marginBottom: SPACING.medium,
    letterSpacing: 0.2,
    paddingHorizontal: SPACING.medium,
    paddingVertical: SPACING.small,
    borderRadius: 2,
    alignSelf: 'flex-start',
  },
  sectionTitleheader: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.LIGHT_TEXT,
    marginBottom: SPACING.medium,
    letterSpacing: 0.2,
    backgroundColor: COLORS.ACCENT,
    paddingHorizontal: SPACING.large,
    paddingVertical: SPACING.small,
    borderRadius: 0,
    width: '100%',
    marginHorizontal: 0,
  },
  darkSectionTitle: {
    color: COLORS.DARK_TEXT,
    backgroundColor: COLORS.DARK_GRAY,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.LIGHT_TEXT,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    paddingHorizontal: SPACING.medium,
    marginHorizontal: SPACING.large,
  },
  darkSearchContainer: {
    backgroundColor: COLORS.DARK_GRAY,
    borderColor: COLORS.DARK_TEXT,
  },
  searchIcon: {
    marginRight: SPACING.small,
  },
  input: {
    flex: 1,
    paddingVertical: SPACING.medium,
    paddingRight: 40,
    fontSize: 16,
    color: COLORS.LIGHT_TEXT,
    backgroundColor: 'transparent',
  },
  darkInput: {
    color: COLORS.DARK_TEXT,
  },
  clearButton: {
    position: 'absolute',
    right: SPACING.medium,
    justifyContent: 'center',
    alignItems: 'center',
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  darkClearButton: {
    backgroundColor: 'transparent',
  },
  categoriesContainer: {
    flexDirection: 'row',
  },
  categoryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: SPACING.medium,
    paddingHorizontal: SPACING.large,
    borderRadius: 20,
    marginRight: SPACING.small,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  darkCategoryButton: {
    backgroundColor: COLORS.DARK_GRAY,
    borderColor: COLORS.DARK_BORDER,
  },
  activeCategoryButton: {
    backgroundColor: COLORS.ACCENT,
    borderColor: COLORS.PRIMARY,
  },
  categoryText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.GRAY,
  },
  darkCategoryText: {
    color: COLORS.BORDER,
  },
  activeCategoryText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  colorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  colorCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: SPACING.medium,
    marginBottom: SPACING.small,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  darkColorCircle: {
    borderColor: COLORS.DARK_BORDER,
  },
  selectedColorCircle: {
    borderWidth: 2,
    borderColor: COLORS.LIGHT_TEXT,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.medium,
  },
  gridItem: {
    width: cardWidth,
    marginBottom: 4,
  },
  gridItemLeft: {
    marginRight: 4,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    height: cardWidth * 1.6,
  },
  imageContainer: {
    width: '100%',
    height: cardWidth * 0.9,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  noImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  noImageText: {
    fontSize: 14,
    color: COLORS.GRAY,
    fontWeight: '500',
  },
  contentContainer: {
    padding: SPACING.medium,
    height: cardWidth * 0.7,
    justifyContent: 'flex-start',
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.LIGHT_TEXT,
    marginBottom: 4,
    height: 40,
    overflow: 'hidden',
  },
  price: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.PRIMARY,
    marginBottom: 4,
    height: 20,
  },
  description: {
    fontSize: 12,
    color: COLORS.GRAY,
    marginBottom: 4,
    height: 32,
    overflow: 'hidden',
  },
  companyText: {
    fontSize: 12,
    color: COLORS.DARK_GRAY,
    fontStyle: 'italic',
    height: 16,
    overflow: 'hidden',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    minHeight: 200,
  },
  errorText: {
    fontSize: 16,
    color: COLORS.ERROR,
    textAlign: 'center',
    marginBottom: SPACING.medium,
    fontWeight: '500',
  },
  retryButton: {
    backgroundColor: COLORS.PRIMARY,
    paddingHorizontal: 24,
    paddingVertical: SPACING.medium,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.GRAY,
    textAlign: 'center',
    fontWeight: '500',
  },
  pinnedButtonContainer: {
    position: 'absolute',
    bottom: 70,
    right: 20,
    zIndex: 1000,
  },
  circleButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.ACCENT,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    bottom: 65,
  },
});

export { styles, COLORS, SPACING, width, cardWidth };